export default [
  { keyCode: 40, display: '(' },
  { keyCode: 41, display: ')' },
  { keyCode: 94, display: '^' },
  { keyCode: 55, display: '7' },
  { keyCode: 56, display: '8' },
  { keyCode: 57, display: '9' },
  { keyCode: 47, display: '÷' },
  { keyCode: 52, display: '4' },
  { keyCode: 53, display: '5' },
  { keyCode: 54, display: '6' },
  { keyCode: 42, display: '×' },
  { keyCode: 49, display: '1' },
  { keyCode: 50, display: '2' },
  { keyCode: 51, display: '3' },
  { keyCode: 45, display: '−' },
  { keyCode: 48, display: '0' },
  { keyCode: 46, display: '.' },
  { keyCode: 13, display: '=' },
  { keyCode: 43, display: '+' }
]
